# Generated by Django 4.2.16 on 2024-10-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='owner',
            new_name='user',
        ),
    ]
